import { Application } from "express"
import multer from "multer"
import { del, get, patch, post, put, read, write } from "security-express"
import { Context } from "./context"

export function route(app: Application, ctx: Context, secure?: boolean): void {
  const parser = multer()
  app.get("/health", ctx.health.check)
  app.patch("/log", ctx.log.config)
  app.patch("/middleware", ctx.middleware.config)
  app.post("/authenticate", parser.none(), ctx.authentication.authenticate)

  const readRole = ctx.authorize("role", read)
  const writeRole = ctx.authorize("role", write)
  get(app, "/privileges", readRole, ctx.privilege.all, secure)
  put(app, "/roles/:id/assign", writeRole, ctx.role.assign, secure)
  post(app, "/roles/search", readRole, ctx.role.search, secure)
  get(app, "/roles/search", readRole, ctx.role.search, secure)
  get(app, "/roles/:id", readRole, ctx.role.load, secure)
  post(app, "/roles", writeRole, ctx.role.create, secure)
  put(app, "/roles/:id", writeRole, ctx.role.update, secure)
  patch(app, "/roles/:id", writeRole, ctx.role.patch, secure)
  del(app, "/roles/:id", writeRole, ctx.role.delete, secure)

  const readUser = ctx.authorize("user", read)
  const writeUser = ctx.authorize("user", write)
  app.get("/roles", readUser, ctx.role.all)
  app.get("/users", readUser, ctx.user.getUsersOfRole)
  app.post("/users/search", readUser, ctx.user.search)
  app.get("/users/search", readUser, ctx.user.search)
  app.get("/users/:id", readUser, ctx.user.load)
  app.post("/users", writeUser, ctx.user.create)
  app.put("/users/:id", writeUser, ctx.user.update)
  app.patch("/users/:id", writeUser, ctx.user.patch)
  app.delete("/users/:id", writeUser, ctx.user.delete)

  const readAuditLog = ctx.authorize("audit_log", read)
  app.get("/audit-logs", readAuditLog, ctx.auditLog.search)
  app.post("/audit-logs/search", readAuditLog, ctx.auditLog.search)
  app.get("/audit-logs/search", readAuditLog, ctx.auditLog.search)
  app.get("/audit-logs/:id", readAuditLog, ctx.auditLog.load)

  const readLocale = ctx.authorize("locale", read)
  const writeLocale = ctx.authorize("locale", write)
  app.post("/locales/search", readLocale, ctx.locale.search)
  app.get("/locales/search", readLocale, ctx.locale.search)
  app.get("/locales/:id", readLocale, ctx.locale.load)
  app.post("/locales", writeLocale, ctx.locale.create)
  app.put("/locales/:id", writeLocale, ctx.locale.update)
  app.patch("/locales/:id", writeLocale, ctx.locale.patch)
  app.delete("/locales/:id", writeLocale, ctx.locale.delete)

  const readCurrency = ctx.authorize("locale", read)
  const writeCurrency = ctx.authorize("locale", write)
  app.post("/currencies/search", readCurrency, ctx.locale.search)
  app.get("/currencies/search", readCurrency, ctx.locale.search)
  app.get("/currencies/:id", readCurrency, ctx.locale.load)
  app.post("/currencies", writeCurrency, ctx.locale.create)
  app.put("/currencies/:id", writeCurrency, ctx.locale.update)
  app.patch("/currencies/:id", writeCurrency, ctx.locale.patch)
  app.delete("/currencies/:id", writeCurrency, ctx.locale.delete)

  const readCountry = ctx.authorize("locale", read)
  const writeCountry = ctx.authorize("locale", write)
  app.post("/countries/search", readCountry, ctx.locale.search)
  app.get("/countries/search", readCountry, ctx.locale.search)
  app.get("/countries/:id", readCountry, ctx.locale.load)
  app.post("/countries", writeCountry, ctx.locale.create)
  app.put("/countries/:id", writeCountry, ctx.locale.update)
  app.patch("/countries/:id", writeCountry, ctx.locale.patch)
  app.delete("/countries/:id", writeCountry, ctx.locale.delete)
}
